name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Base Docker Image
      run: |
        docker build -f base.Dockerfile -t ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest .
        docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

    - name: Build and Push Child Docker Image
      run: |
        docker build -f child.Dockerfile -t ghcr.io/${{ github.repository }}/${{ env.CHILD_IMAGE_NAME }}:latest --build-arg BASE_IMAGE=ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest .
        docker push ghcr.io/${{ github.repository }}/${{ env.CHILD_IMAGE_NAME }}:latest

    env:
      IMAGE_NAME: my-base-image
      CHILD_IMAGE_NAME: my-child-image
