name: Docker build and push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

  

      - name: Build and push child image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: child.Dockerfile
          push: true
          cache-from: type=local,src=/tmp/child-cache
          cache-to: type=local,dest=/tmp/child-cache
          target: child
          tags: ghcr.io/${{ github.repository }}:child-${{ github.sha }}
          build-args: |
            BASE_IMAGE=ghcr.io/${{ github.repository }}:base-${{ github.sha }}

      - name: Save cache for base image
        if: steps.cache-base.outputs.cache-hit == 'false'
        run: |
          mkdir -p /tmp/base-cache
          docker save $(docker images -q ghcr.io/${{ github.repository }}:base-${{ github.sha }}) | gzip > /tmp/base-cache/image.tar.gz

      - name: Save cache for child image
        if: steps.build-and-push.outputs.cache-hit == 'false'
        run: |
          mkdir -p /tmp/child-cache
          docker save $(docker images -q ghcr.io/${{ github.repository }}:child-${{ github.sha }}) | gzip > /tmp/child-cache/image.tar.gz
