name: Push Docker images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build base Docker image
        run: |
          docker build -t my-username/my-repo:base -f base.Dockerfile .
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Push base Docker image to GHCR
        run: |
          docker tag my-username/my-repo:base ghcr.io/my-username/my-repo:base
          docker push ghcr.io/my-username/my-repo:base

      - name: Build child Docker image
        run: |
          docker build -t my-username/my-repo:child -f child.Dockerfile .
        
      - name: Push child Docker image to GHCR
        run: |
          docker tag my-username/my-repo:child ghcr.io/my-username/my-repo:child
          docker push ghcr.io/my-username/my-repo:child
